config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get '/about', to: 'static_pages#about'
  resources :notes
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/note.rb
class Note < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  def index
    @notes = Note.order(created_at: :desc)
  end

 

  def show
    @note = Note.find(params[:id])
  end

  def new
    @note = Note.new
  end

  def create 
    @note = Note.new(notes_params)

    if @note.save
      redirect_to notes_path
    else
      render :new
    end
  end

  def edit
    @note = Note.find(params[:id])
  end

  def update
    @note = Note.find(params[:id])
    
    if @note.update(notes_params)
      redirect_to notes_path
    else
      render :edit
    end
  end

  def destroy
    Note.find(params[:id]).destroy
    redirect_to notes_path
  end

  private
   def notes_params
    params.require(:note).permit(:subject, :date, :body, :author)
   end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_navbar.html.erb
<%= link_to 'Home', root_path %>
<%= link_to 'About', about_path %>
<%= link_to 'Notes', notes_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Postit</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body style="background-color:yellow;">
  <%= render 'layouts/navbar' %>
    <%= yield %>
  </body>
</html>

app/views/notes/edit.html.erb
<h1>Edit Note</h1>
<%= form_for @note do |f| %>
    <%= f.label :subject %>
    <%= f.text_field :subject %>
  
    <%= f.label :date %>
    <%= f.text_field :date %>
  
    <%= f.label :body %>
    <%= f.text_area :body %>
  
    <%= f.label :author %>
    <%= f.text_area :author %>
  
    <%= f.submit %>
  <% end %>

app/views/notes/index.html.erb
<h1>Notes</h1>
<% @notes.each do |note| %>
    <h2><%= note.subject %></h2>
    <%= link_to 'Show Note', note_path(note) %>
    <p><%= link_to 'New Note', new_note_path %></p>
    <%= link_to 'Edit Note', edit_note_path(note) %>
    <%= link_to 'Delete Note', note, method: :delete %>
    <% end %>

app/views/notes/new.html.erb
<<h1>New Note</h1>
<%= form_for @note do |f| %>
  <%= f.label :subject %>
  <%= f.text_field :subject %>

  <%= f.label :date %>
  <%= f.text_field :date %>

  <%= f.label :body %>
  <%= f.text_area :body %>

  <%= f.label :author %>
  <%= f.text_area :author %>

  <%= f.submit %>
<% end %>

app/views/notes/show.html.erb
<h1><%= @note.subject %></h1>
<h4><%= @note.date %></h4>
<p><%= @note.body %></p>
<h3>Created By: <%= @note.author %></h3>
<%= link_to 'Back', notes_path %>

app/views/static_pages/about.html.erb
<h1> Sticky Notes! </h1>
<p>Sticky Notes is a registered trademark of
blah blah blah </p>

app/views/static_pages/home.html.erb
<h1>Home</h1>
<p>Welcome to Sticky Notes, prepare to get stuck!!!! </p>